COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SECRETS_MANAGER:
    NAME: "azure-bd-secret"
    REGION: "europe-north"

production:
  <<: *common
  SECRETS_MANAGER:
    NAME: "azure-db-secret"
    REGION: "europe-north"

ADDITIONAL_CONFIG:
  MYSQL_HOST: "74.234.24.16"
  MYSQL_USER: "azureuser"
  MYSQL_PASSWORD: "my_password"
  MYSQL_DB: "weather_db"
